name: CD

on:
  push:
    branches: [ v2 ]
  # workflow_dispatch:

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Compile assets with Gulp
        uses: elstudio/actions-js-build/build@v4

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-files
          path: static

  deploy:
    runs-on: ubuntu-latest
    needs: build-assets
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: static-files
          path: static

      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."
          target: "src/RobotFW-frontend"
          rm: true

      - name: Call remote deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "./gha_deploy.sh robotfw_frontend"
