name: CD

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'assets/**'
    - 'xsl/**'
    - '**.md'
    - 'LICENSE'
    - '.gitignore'
    - 'package*.json'
    - 'tailwind.config.js'
    - 'config-local.xml'
    - 'config-test.xml'
    - 'docker-compose.override.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."
          target: "src/RobotFW-frontend"
          rm: true

      - name: Call remote deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "./gha_deploy.sh robotfw_frontend"
